"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { toast, Toaster } from "sonner";

export default function LoginPage() { const [email, setEmail] = useState(""); const [token, setToken] = useState(""); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const router = useRouter();
  async function sendOtp() { if (!email.includes("@")) return toast.error("Enter a valid email address"); setLoading(true); try { const { error } = await createClient().auth.signInWithOtp({ email, options: { shouldCreateUser: false } }); if (error) throw error; setSent(true); toast.success("Code sent", { description: `Check ${email} for your one-time code.` }); } catch (e) { toast.error("Could not send code", { description: e instanceof Error ? e.message : "Try again" }); } finally { setLoading(false); } }
  async function verify() { setLoading(true); try { const { error } = await createClient().auth.verifyOtp({ email, token, type: "email" }); if (error) throw error; router.push("/coachings"); } catch (e) { toast.error("Invalid code", { description: e instanceof Error ? e.message : "Try again" }); } finally { setLoading(false); } }
  return <><Toaster position="top-right" richColors /><main className="login-wrap"><div className="login-card"><div className="brand" style={{ padding: 0 }}><span className="brand-mark">M</span><span>MentoraCity</span></div><h1>Welcome back</h1><p>Sign in to the admin SEO workspace with your email. No password required.</p>{!sent ? <><input className="login-input" type="email" placeholder="you@company.com" value={email} onChange={(e) => setEmail(e.target.value)} onKeyDown={(e) => e.key === "Enter" && sendOtp()} /><button className="btn btn-primary" style={{ width: "100%" }} disabled={loading} onClick={sendOtp}>{loading ? "Sending…" : "Send one-time code"}</button></> : <><input className="login-input otp" inputMode="numeric" maxLength={6} placeholder="000000" value={token} onChange={(e) => setToken(e.target.value.replace(/\D/g, ""))} onKeyDown={(e) => e.key === "Enter" && verify()} /><button className="btn btn-primary" style={{ width: "100%" }} disabled={loading || token.length !== 6} onClick={verify}>{loading ? "Verifying…" : "Verify and continue"}</button><button className="btn btn-ghost" style={{ width: "100%", marginTop: 8 }} onClick={() => setSent(false)}>Use a different email</button></>}</div></main></>;
}
